#############################################################################
# Makefile for building: VTSLcd
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  VTSLcd.pro
# Template: app
# Command: /home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/qmake -o Makefile VTSLcd.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VTSLcd1.0.0
DISTDIR = /mnt/hgfs/lvgl/code/VTSLcd/.tmp/VTSLcd1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/tiydy/Qt5.14.2/5.14.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/tiydy/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so /home/tiydy/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Gui.so /home/tiydy/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Sql.so /home/tiydy/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		vtslcd.cpp \
		lcdconfig.cpp moc_vtslcd.cpp \
		moc_lcdconfig.cpp
OBJECTS       = main.o \
		vtslcd.o \
		lcdconfig.o \
		moc_vtslcd.o \
		moc_lcdconfig.o
DIST          = /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/linux.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/qconfig.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_post.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/moc.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/uic.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/yacc.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/lex.prf \
		VTSLcd.pro vtslcd.h \
		lcdconfig.h \
		common.h main.cpp \
		vtslcd.cpp \
		lcdconfig.cpp
QMAKE_TARGET  = VTSLcd
DESTDIR       = 
TARGET        = VTSLcd


first: all
####### Build rules

VTSLcd: ui_vtslcd.h ui_lcdconfig.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VTSLcd.pro /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++/qmake.conf /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/linux.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/qconfig.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_post.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/moc.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/uic.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/yacc.prf \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/lex.prf \
		VTSLcd.pro
	$(QMAKE) -o Makefile VTSLcd.pro
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_pre.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/unix.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/linux.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/sanitize.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-base.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/common/g++-unix.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/qconfig.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_functions.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt_config.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/toolchain.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_pre.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resolve_config.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/default_post.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/warn_on.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qt.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources_functions.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/resources.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/moc.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/opengl.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/uic.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/unix/thread.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/qmake_use.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/file_copies.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/testcase_targets.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/exceptions.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/yacc.prf:
/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/lex.prf:
VTSLcd.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile VTSLcd.pro

qmake_all: FORCE


all: Makefile VTSLcd

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents vtslcd.h lcdconfig.h common.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp vtslcd.cpp lcdconfig.cpp $(DISTDIR)/
	$(COPY_FILE) --parents vtslcd.ui lcdconfig.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_vtslcd.cpp moc_lcdconfig.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_vtslcd.cpp moc_lcdconfig.cpp
moc_vtslcd.cpp: vtslcd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlogging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qflags.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmutex.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnumeric.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnamespace.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstring.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qchar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrefcount.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qarraydata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiterator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpair.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvector.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpoint.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregexp.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmetatype.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmargins.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrect.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsize.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpalette.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcolor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgb.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgba64.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qbrush.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qmatrix.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpolygon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qregion.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdatastream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiodevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qline.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtransform.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpainterpath.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qimage.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qshareddata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhash.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfont.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvariant.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdebug.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtextstream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlocale.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qset.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfile.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvector2d.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtouchdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qicon.h \
		common.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QObject \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QTimer \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QFile \
		moc_predefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/moc
	/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/moc $(DEFINES) --include /mnt/hgfs/lvgl/code/VTSLcd/moc_predefs.h -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++ -I/mnt/hgfs/lvgl/code/VTSLcd -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include vtslcd.h -o moc_vtslcd.cpp

moc_lcdconfig.cpp: lcdconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QDialog \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlogging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qflags.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmutex.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnumeric.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnamespace.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstring.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qchar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrefcount.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qarraydata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiterator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpair.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvector.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpoint.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregexp.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmetatype.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmargins.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrect.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsize.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpalette.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcolor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgb.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgba64.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qbrush.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qmatrix.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpolygon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qregion.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdatastream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiodevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qline.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtransform.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpainterpath.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qimage.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qshareddata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhash.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfont.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvariant.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdebug.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtextstream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlocale.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qset.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfile.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvector2d.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtouchdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlQuery \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlError \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlerror.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QDebug \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlTableModel \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqltablemodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquerymodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qabstractitemmodel.h \
		common.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QObject \
		moc_predefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/moc
	/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/moc $(DEFINES) --include /mnt/hgfs/lvgl/code/VTSLcd/moc_predefs.h -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++ -I/mnt/hgfs/lvgl/code/VTSLcd -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql -I/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include lcdconfig.h -o moc_lcdconfig.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_vtslcd.h ui_lcdconfig.h
compiler_uic_clean:
	-$(DEL_FILE) ui_vtslcd.h ui_lcdconfig.h
ui_vtslcd.h: vtslcd.ui \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/uic
	/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/uic vtslcd.ui -o ui_vtslcd.h

ui_lcdconfig.h: lcdconfig.ui \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/uic
	/home/tiydy/Qt5.14.2/5.14.2/gcc_64/bin/uic lcdconfig.ui -o ui_lcdconfig.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp /home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QApplication \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlogging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qflags.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmutex.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnumeric.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstring.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qchar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrefcount.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnamespace.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qarraydata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiterator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpair.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvector.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpoint.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregexp.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmetatype.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qeventloop.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsize.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmargins.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrect.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpalette.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcolor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgb.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgba64.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qbrush.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qmatrix.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpolygon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qregion.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdatastream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiodevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qline.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtransform.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpainterpath.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qimage.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qshareddata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhash.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfont.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvariant.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdebug.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtextstream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlocale.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qset.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfile.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvector2d.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtouchdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlQuery \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlError \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlerror.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QDebug \
		vtslcd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qicon.h \
		common.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QObject \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QTimer \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

vtslcd.o: vtslcd.cpp vtslcd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QMainWindow \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlogging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qflags.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmutex.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnumeric.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnamespace.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstring.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qchar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrefcount.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qarraydata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiterator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpair.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvector.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpoint.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregexp.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmetatype.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmargins.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrect.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsize.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpalette.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcolor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgb.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgba64.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qbrush.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qmatrix.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpolygon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qregion.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdatastream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiodevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qline.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtransform.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpainterpath.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qimage.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qshareddata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhash.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfont.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvariant.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdebug.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtextstream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlocale.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qset.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfile.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvector2d.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtouchdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qicon.h \
		common.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QObject \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QTimer \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasictimer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QFile \
		ui_vtslcd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QVariant \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QAction \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qaction.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QApplication \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qeventloop.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QGridLayout \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QLabel \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlabel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qframe.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QMenu \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qmenu.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QMenuBar \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qmenubar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QStatusBar \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QWidget \
		lcdconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QDialog \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlQuery \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlError \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlerror.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QDebug \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlTableModel \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqltablemodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquerymodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlRecord \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlrecord.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtslcd.o vtslcd.cpp

lcdconfig.o: lcdconfig.cpp lcdconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QDialog \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdialog.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlogging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qflags.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmutex.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnumeric.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qnamespace.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstring.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qchar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrefcount.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qarraydata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiterator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpair.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvector.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qpoint.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringlist.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregexp.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmetatype.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmargins.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qrect.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsize.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpalette.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcolor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgb.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qrgba64.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qbrush.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qmatrix.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpolygon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qregion.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdatastream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qiodevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qline.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtransform.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpainterpath.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qimage.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpixmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qshareddata.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qhash.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfont.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontmetrics.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qfontinfo.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qkeysequence.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qevent.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qvariant.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qmap.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qdebug.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qtextstream.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qlocale.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qset.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurl.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qurlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfile.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvector2d.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtouchdevice.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlQuery \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquery.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlError \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlerror.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QDebug \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlTableModel \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqltablemodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlquerymodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qabstractitemmodel.h \
		common.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QObject \
		ui_lcdconfig.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/QVariant \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QApplication \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qeventloop.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QComboBox \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qcombobox.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qvalidator.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qregularexpression.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qicon.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qslider.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qstyle.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtabbar.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qrubberband.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qframe.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QGridLayout \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QHeaderView \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qheaderview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QLabel \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlabel.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QLineEdit \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qlineedit.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtextcursor.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtextformat.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qpen.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtGui/qtextoption.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QPushButton \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QTableView \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/qtableview.h \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/QSqlRecord \
		/home/tiydy/Qt5.14.2/5.14.2/gcc_64/include/QtSql/qsqlrecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lcdconfig.o lcdconfig.cpp

moc_vtslcd.o: moc_vtslcd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vtslcd.o moc_vtslcd.cpp

moc_lcdconfig.o: moc_lcdconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lcdconfig.o moc_lcdconfig.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/VTSLcd/bin || mkdir -p $(INSTALL_ROOT)/opt/VTSLcd/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/VTSLcd/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/VTSLcd/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/VTSLcd/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/VTSLcd/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

